wifi_ssid: "YOUR WIFI SSID" # Replace with your Wi-Fi network's SSID
wifi_password: "YOUR WIFI PASSWORD" # Replace with your Wi-Fi network's password

ap_ssid: "YOUR AP SSID"
ap_password: "YOUR AP PASSWORD"

mqtt_broker: "YOUR MQTT BROKER"
mqtt_username: "YOUR MQTT USER"
mqtt_password: "YOUR MQTT PASSWORD"